// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUqGV1W0XWzVJA8NufZVjQBg3kMuUds58',
    appId: '1:51331421992:web:dc29205eebfd35d154a21d',
    messagingSenderId: '51331421992',
    projectId: 'todo-store-a7daa',
    authDomain: 'todo-store-a7daa.firebaseapp.com',
    storageBucket: 'todo-store-a7daa.firebasestorage.app',
    measurementId: 'G-X9SM44WDJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdG-zuBEY5pjptOJRlgwZk4Tyj2uQjHKI',
    appId: '1:51331421992:android:f48e549af4ef23e554a21d',
    messagingSenderId: '51331421992',
    projectId: 'todo-store-a7daa',
    storageBucket: 'todo-store-a7daa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHijTIF-YuwCVIyu5heesN54ZTIoOMirI',
    appId: '1:51331421992:ios:45b533f9096a4bb254a21d',
    messagingSenderId: '51331421992',
    projectId: 'todo-store-a7daa',
    storageBucket: 'todo-store-a7daa.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestoreCrudTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHijTIF-YuwCVIyu5heesN54ZTIoOMirI',
    appId: '1:51331421992:ios:45b533f9096a4bb254a21d',
    messagingSenderId: '51331421992',
    projectId: 'todo-store-a7daa',
    storageBucket: 'todo-store-a7daa.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestoreCrudTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUqGV1W0XWzVJA8NufZVjQBg3kMuUds58',
    appId: '1:51331421992:web:80ac09e0c7706b5254a21d',
    messagingSenderId: '51331421992',
    projectId: 'todo-store-a7daa',
    authDomain: 'todo-store-a7daa.firebaseapp.com',
    storageBucket: 'todo-store-a7daa.firebasestorage.app',
    measurementId: 'G-6TQEK4EE4X',
  );
}
